services:
  app:
    image: gotodo
    build:
      args:
        - target=dev
    environment:
      TODO_ENV: dev
      PORT: 8080
      TODO_DB_HOST: todo-db
      TODO_DB_PORT: 5432
      TODO_DB_USER: todo
      TODO_DB_PASSWORD: todo
      TODO_DB_NAME: todo
      TODO_REDIS_HOST: todo-redis
      TODO_REDIS_PORT: 6379
    volumes:
      - .:/app
    ports:
      - "18000:8080"
  todo-db:
    image: postgres:9.6
    container_name: todo-db
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    volumes:
      - todo_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  todo-redis:
    image: "redis:latest"
    container_name: todo-redis
    ports:
      - "36379:6379"
    volumes:
      - todo_redis_data:/data
volumes:
  todo_db_data:
  todo_redis_data: