name: golang-ci
on:
  pull_request:
    paths:
      - "**/*.go"
      - ".github/workflows/golangci.yml"
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.18"

      # Goモジュールのキャッシュをクリーン
      - name: Clear Go mod cache
        run: go clean -modcache
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=.golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"
