name: golang-ci
on:
  pull_request:
    paths:
      - "**/*.go"
      - ".github/workflows/golangci.yml"
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove Go mod directory manually
        run: rm -rf ~/go/pkg/mod

      - name: Clear Go mod cache
        run: go clean -mod cache
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=.golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"
          skip-pkg-cache: true
