on:
  push:
    branches:
      - main
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      todo-db:
        image: postgres:9.6
        env:
          POSTGRES_USER: todo
          POSTGRES_PASSWORD: todo
          POSTGRES_DB: todo
        ports:
          - 5432:5432
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18"
      - uses: actions/checkout@v3
      - run: |
          curl -LO https://github.com/sqldef/sqldef/releases/download/v0.17.17/psqldef_linux_arm64.tar.gz
          tar -xzf psqldef_linux_arm64.tar.gz
          rm psqldef_linux_arm64.tar.gz
          PGPASSWORD=todo ./psqldef -h 127.0.0.1 -U todo todo < ./_tool/postgresql/schema.sql
      - run: go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v1
